name: Docker build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t shopifly
          docker tag shopifly 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1049:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1049:$rev

     # - name: Login to Docker Hub
      #  uses: docker/login-action@v2
       # with:
        #  username: ${{ secrets.DOCKER_HUB_USERNAME }}
         # password: ${{ secrets.DOCKER_HUB_TOKEN }}

      #- name: Build and push docker image to ECR
       # uses: docker/build-push-action@v3
        #with:
         # context: .
          #file: ./Dockerfile
          #push: true
          #tags: ${{ secrets.DOCKER_HUB_USERNAME }}/shopiflai:latest